---

- include_vars: "{{ nvm_env }}.yml"

- include: "system/install.yml"
  when: "nvm_env == 'system'"

- include: "user/install.yml"
  when:  "nvm_env == 'user'"

- name: add nvm initialization to profile
  template: >
    src=nvm.sh.j2
    dest=/etc/profile.d/nvm.sh
    owner=root
    group=root
    mode=0755
  sudo: true

- include: "system/{{ item }}.yml"
  with:
    - "install_versions"
    - "install_packages"
  when: "nvm_env == 'system'"

- include: "user/{{ item }}.yml"
  with:
    - "install_versions"
    - "install_packages"
  when: "nvm_env == 'user'"
